name: weather_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  geolocator: ^13.0.2
  geocoding:  ^3.0.0
  lottie: ^3.0.0
  flutter_bloc: ^8.1.6
  intl: ^0.20.1
  weather: ^3.1.1
  equatable: ^2.0.5
  google_fonts: ^6.1.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
